
name: windows

on: push

jobs:
  python:
    strategy:
      matrix:
        arch: ["32", "64"]
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: prepare python
        run: |
          echo hello
          
      - name: publish to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: xmake-mirror/openssl
          repo_token: ${{ secrets.XMAKE_REPO_TOKEN }}
          file: README.md
          asset_name: READNE.win${{ matrix.arch }}.md
          tag: "3.9.5"
          body: "test body 3.9.5"
